{
 "title": "TM",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RfInvoker ThreadPool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "hystrix_threadpool_threads_active_current_count{key=\"RfInvoker\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hystrix_threadpool_threads_max_pool_current_size{key=\"RfInvoker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BpmExecutor ThreadPool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "hystrix_threadpool_threads_active_current_count{key=\"BpmExecutor\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hystrix_threadpool_threads_max_pool_current_size{key=\"BpmExecutor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PCE_JDBC_TX_DATASOURCE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "agroal_active_count{name=\"PCE_JDBC_TX_DATASOURCE\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "agroal_available_count{name=\"PCE_JDBC_TX_DATASOURCE\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "JVM Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "jvm_memory_usage_after_gc_percent",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RFInvoker Request Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "hystrix_threadpool_queue_current_size{key=\"RfInvoker\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hystrix_threadpool_queue_rejection_threshold_size{key=\"RfInvoker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BpmExecutor Request Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 8 },
   "targets": [
    {
     "expr": "hystrix_threadpool_queue_current_size{key=\"BpmExecutor\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hystrix_threadpool_queue_rejection_threshold_size{key=\"BpmExecutor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 8 },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "__auto" }
   ]
  }
 ]
}